[package]
name = "pkb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = { version = "0.12.1", default-features = false, features = ["syntect"] }
markup = { git = "https://github.com/wezm/markup.rs.git", rev = "19cfdf8" }
rocket = { version = "0.5.0-rc.1" } #, features = ["secrets", "json"] }
sentry = { version = "0.25.0", default-features = false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.23"
time = { version = "0.3.5", features = ["formatting"] } # should match rocket
titlecase = "1.1"

[patch.crates-io]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "66d18bf" }
