[package]
name = "pkb"
version = "2.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = { version = "0.12.1", default-features = false, features = ["syntect"] }
deunicode = "1.3"
html5ever = "0.25.2"
kuchiki = "0.8.1"
markup = { git = "https://github.com/wezm/markup.rs.git", rev = "19cfdf8" }
rocket = { version = "0.5.0-rc.1" }
sentry = { version = "0.25.0", default-features = false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.23"
sitemap = { git = "https://github.com/wezm/rust-sitemap-time.git", rev = "96d0d81" }
time = { version = "0.3.5", features = ["std", "formatting", "parsing", "macros"] } # version should match rocket
titlecase = "1.1"

[build-dependencies]
time = { version = "0.3.5", features = [] } # version should match above

[dev-dependencies.regex]
version = "1.5"
default-features = false
features = ["std"]

[patch.crates-io]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "66d18bf" }
