[default]
pages_path = "pages"
author = "Some One"
author_url = "http://example.com/"
copyright_start_year = 2022
name = "Site Name"
domain = "example.com"
tagline = "A short tagline"
# sentry_dsn = "your dsn" # optional
